Completed armors and weapons, and fixed text
SeeSharpCode/zEdit-patchus-maximus pull request #23
Opened 2019-01-17 04:00 UTC by smk291

2019-01-18 20:13 UTC, SeeSharpCode reviewed
After looking at these changes and the existing config files, I'm thinking about changing the structure a bit to move away from arrays and towards objects.

For example, changing from this:
```js
[
  {
    "name": "common",
    "nameSubstrings": ["Common"],
    "factorArmor": 1,
  },
  {
    "name": "alduin",
    "nameSubstrings": ["Alduin"],
    "factorArmor": 1,
  }
]
```
to this:
```js
{
  "common": {
    "nameSubstrings": ["Common"],
    "factorArmor": 1,
   },
  "alduin": {
    "nameSubstrings": ["Alduin"],
    "factorArmor": 1,
   }
}
```

Thoughts? I think it makes more sense in JS and will make the config code easier.

2019-01-18 20:30 UTC, SeeSharpCode requested changes
I'd like to leave only crafting material-related config in the `materials` folder. Mind moving the new armor/weapon stuff you added to new `config/armor` and `config/weapons` folders? Also, the exclusion files can go in `config\exclusions`.

2019-01-18 21:11 UTC, SeeSharpCode commented on config/materials/armorReforgeExclusions.json
> +{
The exclusions system uses RegEx patterns (see [potions.json](https://github.com/SeeSharpCode/zEdit-patchus-maximus/blob/master/config/exclusions/potions.json). So instead of having `CONTAINS/EQUALS/STARTSWITH`, you can just have RegEx patterns. Using "Spellbreaker" as an example:
- `CONTAINS` would be "Spellbreaker"
- `EQUALS` would be "^Spellbreaker$"
- `STARTSWITH` would be "^Speallbreaker"

2019-01-20 07:49 UTC, SeeSharpCode commented on config/exclusions/armorReforgeExclusions.json
> +        "Spellbreaker": true,
One more thing I forgot to mention. The exclusion names/EDIDs RegEx patterns should be in an array. They you won't need the `: true`.

2019-01-20 19:50 UTC, smk291 commented on config/exclusions/armorReforgeExclusions.json
> +        "Spellbreaker": true,
Done

2019-01-21 01:02 UTC, SeeSharpCode approved these changes

2019-01-21 01:02 UTC, merged